name: Execute Snowflake SQL Files

on:
  push:
    paths:
      - '**/*.sql'
    branches:
      - prod

jobs:
  run-snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Snowflake Connector
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install snowflake-connector-python==3.0.3

      - name: Execute latest SQL file on Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          latest_sql_file=$(find . -name '*.sql' | sort | tail -n 1)
          echo "Executing SQL file: $latest_sql_file"

          echo "
import os
import snowflake.connector

print('Connecting to Snowflake...')
conn = snowflake.connector.connect(
    user=os.environ['SNOWFLAKE_USER'],
    password=os.environ['SNOWFLAKE_PASSWORD'],
    account=os.environ['SNOWFLAKE_ACCOUNT']
)

print('Selecting context...')
conn.cursor().execute(f\"USE DATABASE {os.environ['SNOWFLAKE_DATABASE']}\")
conn.cursor().execute(f\"USE SCHEMA {os.environ['SNOWFLAKE_SCHEMA']}\")
conn.cursor().execute(f\"USE WAREHOUSE {os.environ['SNOWFLAKE_WAREHOUSE']}\")
print('Context selected.')

with open('$latest_sql_file', 'r') as file:
    sql_script = file.read()

for stmt in sql_script.split(';'):
    if stmt.strip():
        print(f'Executing statement: {stmt.strip()}')
        conn.cursor().execute(stmt)

conn.close()
print('âœ… SQL execution completed.')
" > run_script.py

          python3 run_script.py
